### ISSUE TITLE
want to use recoginizer with captured string

### ISSUE THREAD

**Issue by ogata-k** [2000calories/flutter_easy_rich_text#11]
i want to use recoginizer with captured string.

now: 
`
EasyRichTextPattern(
 recognizer: TapGestureRecognizer()
      ..onTap = (){
...
      }
    );
`

change to:
`
EasyRichTextPattern(
 recognizer: (String captured) => TapGestureRecognizer()
      ..onTap = (){
...
      }
    );
`

can do it ?

**Comment by 2000calories** [comment]
What do you mean "captured string"?

**Comment by ogata-k** [comment]
url, email, tel number and so on

**Comment by 2000calories** [comment]
the captured string is not the targetString?

**Comment by ogata-k** [comment]
No.
"captured string" is the str variable in this dwfault  url-luncher function.
`
TapGestureRecognizer tapGestureRecognizerForUrls(String str, String urlType) {
    TapGestureRecognizer tapGestureRecognizer;
    switch (urlType) {
      case 'web':
        if (str.substring(0, 4) != "http") {
          str = "https://$str";
        }
        tapGestureRecognizer = TapGestureRecognizer()
          ..onTap = () {
            _launchURL(str);
          };
        break;
      case 'email':
        tapGestureRecognizer = TapGestureRecognizer()
          ..onTap = () {
            _launchURL("mailto:$str");
          };
        break;
      case 'tel':
        tapGestureRecognizer = TapGestureRecognizer()
          ..onTap = () {
            _launchURL("tel:$str");
          };
        break;
      default:
    }
    return tapGestureRecognizer;
  }
`

if targetString is regex pattern's string, then captured string by the regex.

**Comment by 2000calories** [comment]
Sorry for the late response. Basically the `str` variable is the targerString. If not, the recognizer will not be triggered.

**Comment by ogata-k** [comment]
Then, if ```urlType``` is``` url```, can I use a self-defined function of type ```Future <void> Function (String)```?
I want to use targetString as arg of the self-defined function.

**Comment by 2000calories** [comment]
If you do not want the default url behaviour then do not use the `urlType` option, do what you want in the recognizer.
```
printTargetString(targetString) {
  print(targetString);
}
```
`var targetString = "https://pub.dev/packages/easy_rich_text";`
```
EasyRichText(
  "Here is a website https://pub.dev/packages/easy_rich_text. Here is a email address test@example.com. Here is a telephone number +852 12345678.",
  patternList: [
    EasyRichTextPattern(
      targetString: targetString,
      // urlType: 'web',if you do not want the default behaviour then do not use this option, do what you want in the recognizer.
      style: TextStyle(
        decoration: TextDecoration.underline,
      ),
      recognizer: TapGestureRecognizer()
        ..onTap = () => printTargetString(targetString),
    ),
  ],
),
```

**Comment by ogata-k** [comment]
Is it same the way when use regex？
