### ISSUE TITLE
Enhancement request for converting EasyRichText to String post format

### ISSUE THREAD

**Issue by swapnilkadam18** [2000calories/flutter_easy_rich_text#12]
EasyRichText cannot be type casted to string(plain text) to be used directly whereas RichText has option to convert the modified string to the plain text. 
Objective: Whenever we add superscript / subscript the output we get is a widget(EasyRichText) which cannot be used in where input type is String. Unicodes do help a lot but there are not unicodes for every character hence this library is perfect to avoid unicodes to almost 100%.
Expected Output: Type casting for EasyRichText to String with sub/super script. 

Sincere request.

**Comment by 2000calories** [comment]
I use Transform widget inside EasyRichText and I did not find a solution to convert it to String. Actually, this is a problem trouble me from the beginning. As far as I know unicode is the only option to ouput String Type.
