### ISSUE TITLE
a character under text and list string in targetString

### ISSUE THREAD

**Issue by bang-zoel** [2000calories/flutter_easy_rich_text#13]
hi sir, i have 2 questions:
1. is it possible to use a list for targetString. ex: targetString: ['exposured', 'cen be help', 'working', 'night shift']. because all have same text decoration.
2. can i put a character under text such as in the image bellow:
![question](https://user-images.githubusercontent.com/77826694/106062555-8520ba00-6129-11eb-9505-9ee37e46a2a3.jpg)

**Comment by 2000calories** [comment]
1. good suggestion, I will add this function in next version. 
2. too complicated for this package

**Comment by bang-zoel** [comment]
thank you

**Comment by 2000calories** [comment]
solved in `0.5.5`
