### ISSUE TITLE
FormatException: Unmatched ')'(@一瞬流星:))

### ISSUE THREAD

**Issue by zhongxuerui521** [2000calories/flutter_easy_rich_text#16]
FormatException when targetString contain special  character in EasyRichTextPattern 

#0 new _RegExp (dart:core-patch/regexp_patch.dart:217)
--
2 #1 new RegExp (dart:core-patch/regexp_patch.dart:27)
3 #2 EasyRichText.processStrList.<anonymous closure> (package:easy_rich_text/src/easy_rich_text.dart:214)
4 #3 ListMapView.forEach (dart:_internal/list.dart:242)
5 #4 EasyRichText.processStrList (package:easy_rich_text/src/easy_rich_text.dart:145)
6 #5 EasyRichText.build (package:easy_rich_text/src/easy_rich_text.dart:327)
7 #6 StatelessElement.build (package:flutter/src/widgets/framework.dart:4701)

**Comment by 2000calories** [comment]
set ·hasSpecialCharacters: true,·
