### ISSUE TITLE
Feature Request: Add case insensitive search for targetString

### ISSUE THREAD

**Issue by woelmer** [2000calories/flutter_easy_rich_text#2]
It would be nice if you could specify in the EasyRichTextPattern to perform a case insensitive match of the targetString. If I set a targetString of "michigan" it would style "**Michigan**, USA"

**Comment by 2000calories** [comment]
Set `caseSensitive: false`. You can check the updated example here.
https://github.com/2000calories/flutter_easy_rich_text#case-sensitivity-default-true

**Comment by woelmer** [comment]
Awesome thanks for the quick turnaround!
