### ISSUE TITLE
textScaleFactor overrides OS-Settings

### ISSUE THREAD

**Issue by malmi** [2000calories/flutter_easy_rich_text#20]
The `textScaleFactor` property on `EasyRichText` sets scale factor on a hardcoded value (1.0) if it is null. The default value should be `MediaQuery.of(context).textScaleFactor`, because the user could change the scale factor in the settings menu for accessibility. 

Is it possible to change the hardcoded value to the dynamic value from MediaQueryData?

**Comment by 2000calories** [comment]
Since the the default `textScaleFactor` in `RichText` is 1.0, I prefer not to change the default value considering the purpose of this Widget.

**Comment by malmi** [comment]
Just that i understand it correctly, `RichText` can't support this: 
- https://developer.apple.com/design/human-interface-guidelines/accessibility/overview/text-size-and-weight/
- https://support.apple.com/en-us/HT202828. 
 
The only workaround would be to set the textScaleFactor manually on every usage, because it's overriding the correct textScaleFactors that the TextTheme would otherwise have. It's a source of bugs or at least rendering issues, because every other text-widget will scale correctly except `RichText`.
