### ISSUE TITLE
连续的正则匹配,三个以上只能显示第一个,内部有个判断错误

### ISSUE THREAD

**Issue by wenchang1989** [2000calories/flutter_easy_rich_text#21]
easy_rich_text文件 273行 <= 改为<, 问题解决

期待你的新版本

**Comment by 2000calories** [comment]
Hi 哥们，“<= 改为<” 不影响其他功能，`v0.5.7`更新按这个改了。能给个例子吗，不太清楚你说的问题是什么。

**Comment by wenchang1989** [comment]
四个连续的表情,匹配的时候,只能匹配到第一个,三个连续表情没问题

**Comment by Govita** [comment]
请把你的`EasyRichText`的示例代码发出来一下

**Comment by 2000calories** [comment]
请把你的`EasyRichText`的示例代码发出来一下。

**Comment by 2000calories** [comment]
Closed due to no further feedback.
