### ISSUE TITLE
Need help with making WhatsApp like formatting / italic / bold / underline

### ISSUE THREAD

**Issue by developer-farhan** [2000calories/flutter_easy_rich_text#22]
im trying to get bold and italic and underline formatting like WhatsApp and im using the following but im getting no result

patternList: [
///bold font
EasyRichTextPattern(
targetString: '(\)(.?)(\)',
matchBuilder:
(BuildContext context, RegExpMatch match) {
print(match[0]);
return TextSpan(
text: match[0].replaceAll('', ''),
style:
TextStyle(fontWeight: FontWeight.bold),
);
},
),

                          ///italic font
                          EasyRichTextPattern(
                            targetString: '(\_)(.*?)(\_)',
                            matchBuilder:
                                (BuildContext context, RegExpMatch match) {
                              print(match[0]);
                              return TextSpan(
                                text: match[0].replaceAll('_', ''),
                                style:
                                    TextStyle(fontStyle: FontStyle.italic),
                              );
                            },
                          ),
                        ],

<img width="216" alt="Screenshot 2021-10-13 at 13 37 02" src="https://user-images.githubusercontent.com/82877513/137274177-4a4edc08-c6a1-4a89-b3e6-145ae02a2221.png">
the other text turns black idk why when default color is white
could you help me out

**Comment by officialFlutterDeveloper** [comment]
@2000calories  do keep me posted please prompt fix would be very well appreciated

**Comment by officialFlutterDeveloper** [comment]
is it possible I can use the text changing in textfield? just like how WhatsApp does ? so people can play around before they even send it

**Comment by 2000calories** [comment]
i think you cannot use `RichText` widget as input of `TextFeld` widget. Perhaps you can show the `RichText` widget as a preview just above the `TextFeld` widget if special format were detected in the input.

**Comment by radheyshyamjat** [comment]
With extend this one anyone please help me to implement both at a time like *_Bold Plus Italic_*

**Comment by radheyshyamjat** [comment]
> With extend this one anyone please help me to implement both at a time like *_Bold Plus Italic_*

This also resolve it's just a matter or regex it's very good package for use formatting
If anyone required help posting correct answer also

`            EasyRichTextPattern(
              targetString: '([*_~]{3})(.*?)([_*~])',
              matchBuilder: (BuildContext context, RegExpMatch? match) {
                return TextSpan(
                  text: gerReplacedTextBoldItalicStrike(match?[0]),
                  style: TextStyle(
                      fontStyle: FontStyle.italic,
                      fontWeight: FontWeight.bold,
                      decoration: TextDecoration.lineThrough),
                );
              },
            ),`

`  String gerReplacedTextBoldItalicStrike(String? msg){
    String? msgString = msg;
    if(msgString == null) return "";
    msgString = msgString.replaceAll("*", "");
    msgString = msgString.replaceAll("_", "");
    msgString = msgString.replaceAll("~", "");
    return msgString;
  }
`
