### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by xingfukun** [2000calories/flutter_easy_rich_text#31]
../../../../Desktop/flutter/.pub-cache/hosted/pub.flutter-io.cn/easy_rich_text-1.0.4/lib/src/easy_rich_text.dart:537:9: Error: No named parameter with the name 'semanticsLabel'.

**Comment by 2000calories** [comment]
Please provide `flutter doctor` output.

**Comment by xingfukun** [comment]
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.4 20F71 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.5.3 at /Users/frank/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 months ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/frank/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • ANDROID_HOME = /Users/frank/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (3 available)
    • HLK AL00 (mobile) • C7YVB20317006912          • android-arm64  • Android 10 (API 29)
    • iPhone (mobile)   • 00008020-0008455C2252002E • ios            • iOS 15.0.2 19A404
    • Chrome (web)      • chrome                    • web-javascript • Google Chrome 98.0.4758.80

• No issues found!

**Comment by 2000calories** [comment]
Can you try upgrade Flutter to a newer version? I have tested it on flutter 2.8 and 2.10.

**Comment by 2000calories** [comment]
or clear pub-cache and try it again.

**Comment by xingfukun** [comment]
ok

**Comment by xingfukun** [comment]
编译倒是可以了，但是无法匹配链接高亮：准确来说无法匹配带有参数的链接


EasyRichText(
            "https://baidu.com?test=123 https://google.com",
            patternList: [
              EasyRichTextPattern(
                targetString: "https://baidu.com?test=123",
                style:
                    TextStyle(color: Colors.red, fontWeight: FontWeight.w500),
              ),
              EasyRichTextPattern(
                targetString: "https://google.com",
                style:
                    TextStyle(color: Colors.red, fontWeight: FontWeight.w500),
              ),
            ],
          )

**Comment by xingfukun** [comment]
解决了

**Comment by 2000calories** [comment]
那就好。可以的话，麻烦点个星^_^
