### ISSUE TITLE
adding dollor sign ($) for target string dont work

### ISSUE THREAD

**Issue by sianami** [2000calories/flutter_easy_rich_text#32]
hi
when i add dollor sign ($) to end of string it doesnt work
without $ works fine
how change style of $ too?
targetString: '${userData['invoiceAll']\$}',

and i think styles didn't effect on list variables
this var has a list of numbers that show but arent red
EasyRichTextPattern(
                          targetString: '${userData['numbers']}',
                          style: TextStyle(fontSize: 20, color: Colors.red),
                        ),

**Comment by 2000calories** [comment]
Have you try set `hasSpecialCharacters: true` ?
