### ISSUE TITLE
Not working on web 

### ISSUE THREAD

**Issue by Bockey1999** [2000calories/flutter_easy_rich_text#34]
<img width="1440" alt="Screenshot 2022-06-26 at 18 56 54" src="https://user-images.githubusercontent.com/86289309/175827597-78439da3-a55c-4682-9f2b-4624a02f13f1.png">
This is what it shows when I deploy on to the web while locally it show the text

**Comment by 2000calories** [comment]
Please show your code and flutter doctor output.

**Comment by Bockey1999** [comment]
import 'package:easy_rich_text/easy_rich_text.dart';
import 'package:flutter/material.dart';

class testing extends StatefulWidget {
  const testing({Key? key}) : super(key: key);

  @override
  State<testing> createState() => _testingState();
}

class _testingState extends State<testing> {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: EasyRichText(
        "I want blue color here. I want no blue font here. I want blue invalid here.",
        patternList: [
          EasyRichTextPattern(
            targetString: 'blue',
            stringBeforeTarget: 'want',
            stringAfterTarget: "color",
            style: TextStyle(color: Colors.blue),
          ),
        ],
      ),
    );
  }
}
<img width="1440" alt="Screenshot 2022-06-28 at 10 43 24" src="https://user-images.githubusercontent.com/86289309/176148119-89247581-6533-4a81-850a-5cd921200cf3.png">

**Comment by 2000calories** [comment]
The issue is only on Safari, am I right? 
Safari does not support lookahead and behind RegExp, which is required for conditional search in EasyRichText.

**Comment by 2000calories** [comment]
closed since no further feedback
