### ISSUE TITLE
special characters don't take effect!

### ISSUE THREAD

**Issue by Espero1995** [2000calories/flutter_easy_rich_text#36]
I found that after setting hasSpecialCharacters: true, the original matching ordinary characters did not take effect, and the special symbols were not set to the highlighted state.

**Comment by 2000calories** [comment]
Can you post an example?

**Comment by Espero1995** [comment]
Like .  - 
![image](https://user-images.githubusercontent.com/19235464/185829027-f18c8feb-8179-4c66-9cbc-77e76d3f7894.png)
<img width="366" alt="image" src="https://user-images.githubusercontent.com/19235464/185829041-e48d159c-321e-4e59-b500-47e2f52a5f5b.png">

**Comment by Espero1995** [comment]
是因为特殊字符串和其他字符连续的原因嘛？我对特殊字符后面加空格好像就能正常高亮显示了。在已解决的issue里我看到的电话号码99+的是因为后面有个空格，所以才高亮了，但是我去掉空格发现也是没有高亮的

**Comment by 2000calories** [comment]
```
    EasyRichText(
      "Received 1-1-2 messages. Received 1.1.2 messages.",
      patternList: [
        EasyRichTextPattern(
          targetString: '1-',
          matchWordBoundaries: false,
          style: const TextStyle(color: Colors.red),
        ),
      ],
    ),

    EasyRichText(
      "Received 1-1-2 messages. Received 1.1.2 messages.",
      patternList: [
        EasyRichTextPattern(
          targetString: '1.',
          hasSpecialCharacters: true,
          matchWordBoundaries: false,
          style: const TextStyle(color: Colors.red),
        ),
      ],
    ),
```
要在 `1-1-2` 连续的字符串中匹配部分字符串`1-`，要设置`matchWordBoundaries: false,`

**Comment by Espero1995** [comment]
OK了，非常感谢
