### ISSUE TITLE
Apply Styling in nested EasyRichTextPattern

### ISSUE THREAD

**Issue by nawaf11** [2000calories/flutter_easy_rich_text#39]
Welcome, Many Thanks for the Library

I want to do styling in nested EasyRichTextPattern..

for Example any text between "" to be red, And {[..]} to be blue even if it found between "..", Check the image:

<img width="381" alt="image" src="https://user-images.githubusercontent.com/17469798/200138021-213d7cf1-06a2-4273-9a95-32d2f5315efc.png">

iI have this patternList:

`
patternList = [
EasyRichTextPattern(targetString: '"(.+?)"', style: TextStyle(color: darkRed)),
EasyRichTextPattern(targetString: "(\\{\\[(\.+?)\\]\\})", style: TextStyle(color: primaryGreen))
]
`

**Comment by nawaf11** [comment]
I hope there's a Plan to this enhancement 🙏🏻

**Comment by 2000calories** [comment]
It is a useful feature. But I have not find a way to implement it.

**Comment by 2000calories** [comment]
try the latest version.
```easy_rich_text: '^2.0.0'```
