### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by tasselx** [2000calories/flutter_easy_rich_text#4]
1. Some text with the same content and I only match the first one, or one of them, or all of them
2. Some text can support adding response events

**Comment by 2000calories** [comment]
2. Some text can support adding response events

Url Launcher
Integrated with url_launcher. Web url, email url, and telephone url are supported. Set urlType : 'web', 'email', or 'tel'. EasyRichText provides regular expression formula to match common urls.
https://github.com/2000calories/flutter_easy_rich_text#url-launcher

GestureRecognizer
https://github.com/2000calories/flutter_easy_rich_text#gesturerecognizer

**Comment by 2000calories** [comment]
1. Some text with the same content and I only match the first one, or one of them, or all of them
try the latest version.
https://github.com/2000calories/flutter_easy_rich_text#match-option

**Comment by tasselx** [comment]
Thank you very much for your quick response, I've verified that I closed the issue!
