### ISSUE TITLE
FormatException: Range out of order in character class

### ISSUE THREAD

**Issue by Alexander-TM** [2000calories/flutter_easy_rich_text#40]
Flutter throwing this exception:

```
The following FormatException was thrown building EasyRichText(dirty):
Range out of order in character class((?<!\w)qu'y a-t-il? [ou qu'est-ce qu'il y a?] ― il y a que j'ai faim!(?!\w))
```

**Comment by 2000calories** [comment]
Please show your flutter doctor output.

**Comment by Alexander-TM** [comment]
I'm using VS Code and testing on android device.

[✓] Flutter (Channel stable, 3.3.10, on Mac OS X 10.15.7 19H2026 darwin-x64, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    ✗ Flutter requires Xcode 13 or higher.
      Download the latest version or update via the Mac App Store.
    ! CocoaPods 1.10.1 out of date (1.11.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2022.1.2)
[✓] VS Code (version 1.74.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by 2000calories** [comment]
I do not see any error after upgrading to  3.3.10. Please show your widget code.

**Comment by Alexander-TM** [comment]
The code:
===============================================================
`Flexible(
              child: EasyRichText(
                trans.source + ": " + trans.targetObj.text!,
                patternList: [
                  EasyRichTextPattern(
                      targetString: trans.source,
                      style: const TextStyle(
                        fontStyle: FontStyle.italic, fontSize: 15,
                        // color: Colors.grey.shade700
                      )),
                  EasyRichTextPattern(
                      targetString: trans.targetObj.text,
                      style: TextStyle(
                          fontWeight: FontWeight.bold,
                          fontSize: 15,
                          // backgroundColor: globals.genderColors[trans.targetObj.gender]
                          color: globals.genderColors[trans.targetObj.gender]))
                ],
              ),
            ),`
===============================================================

It works perfectly until it stumbles upon this following json block in french, is there a character that's causing this exception?

==================================================================

"source": "<span class=\"example\">qu&#39;y a-t-il? [<span class=\"or\"><acronym title=\"ou\">ou</acronym></span> qu&#39;est-ce qu&#39;il y a?] ― il y a que j&#39;ai faim!</span>",
                                        "target": "what&#39;s the matter? ― I&#39;m hungry, that&#39;s what!"

**Comment by Alexander-TM** [comment]
It worked thank you
