### ISSUE TITLE
Cannot match Arabic characters

### ISSUE THREAD

**Issue by tasselx** [2000calories/flutter_easy_rich_text#5]
![6418E045-CAA4-49D2-8A6E-3010BE1A792A](https://user-images.githubusercontent.com/2656142/88265608-649e2000-cd00-11ea-92c2-63f7af3dc3a4.png)

```
 EasyRichText(
                "الحياة أكثر من مجرد الحاضر",
                patternList: [
                  EasyRichTextPattern(
                    targetString: 'من',
                    style: TextStyle(color: Colors.blue),
                  )
                ],
                defaultStyle: TextStyle(color: Colors.red),
              ),
```

**Comment by 2000calories** [comment]
Arabic character is strange >.<
I cannot fix this right now. Need more time to look into it.

**Comment by tasselx** [comment]
> Arabic character is strange >.<
> I cannot fix this right now. Need more time to look into it.

Well our user group has some Arabic , so still looking forward to the problem can be solved , if you need my help to test it , I have been online , thank you very much open source code flutter comes with rich text needs to be stitched , or do not like it .

**Comment by 2000calories** [comment]
try the develop branch.
```
easy_rich_text:
    git:
      url: https://github.com/2000calories/flutter_easy_rich_text.git
      ref: develop
```

**Comment by tasselx** [comment]
> try the develop branch.
> 
> ```
> easy_rich_text:
>     git:
>       url: https://github.com/2000calories/flutter_easy_rich_text.git
>       ref: develop
> ```
Awesome, I tried it and it works, it matches to Arabic characters

**Comment by 2000calories** [comment]
Just a reminder, please switch to the lastest version instead of the develop branch.

```
dependencies:
  easy_rich_text: ^0.3.3
```
