### ISSUE TITLE
Reverse changelog order

### ISSUE THREAD

**Issue by dhafinrayhan** [2000calories/flutter_easy_rich_text#53]
Currently, the changelog is shown with the very first version on the top, and the latest version on the bottom. We need to reverse it so that the latest version appears on the top (as in most other packages).

Example from package `http`: https://pub.dev/packages/http/changelog

**Comment by dhafinrayhan** [comment]
I don't understand why this issue was closed. It's not fixed yet... I can see in the [changelog page](https://pub.dev/packages/easy_rich_text/changelog) it's still starting from the earliest version, not from the latest one.

@2000calories

**Comment by 2000calories** [comment]
I don't consider this to be an "issue" as it does not affect the implementation or any functions. I'll probably follow your advice next time I update the package. You can pull a request if you want.

**Comment by 2000calories** [comment]
Starting from `v2.2.0`, the changelog is displayed in descending order
