### ISSUE TITLE
When we us special characters in EasyRichText as Target String like ~|[]{}#%^*+=_|<>$£€•.,?!’ it crashes & fires exception.

### ISSUE THREAD

**Issue by nirajjoshi** [2000calories/flutter_easy_rich_text#7]
@2000calories :

When we us special characters in EasyRichText as **Target String** like **~|[]{}#%^*+=_|<>$£€•.,?!’** it crashes & fires below mentioned exception.
Please refer screenshot from your example app only.

```
///GestureRecognizer, not working when superscript, subscript, or urlType is set.
              ///TapGestureRecognizer, MultiTapGestureRecognizer, etc.
              EasyRichText(
                "Tap recognizer to print this sentence.~|[]{}#%^*+=_\|<>\$£€•.,?!’",
                patternList: [
                  EasyRichTextPattern(
                    targetString: '~|[]{}#%^*+=_\|<>\$£€•.,?!’',
                    recognizer: TapGestureRecognizer()
                      ..onTap = () {
                        print("Tap recognizer to print this sentence.");
                      },
                    style: TextStyle(
                      decoration: TextDecoration.underline,
                    ),
                  ),
                ],
              ),
```
════════ Exception caught by widgets library ═══════════════════════════════════
The following FormatException was thrown building EasyRichText(dirty, dependencies: [DefaultTextStyle]):
Lone quantifier **brackets((?<!\w)~|[]{}#%^*+=_|<>$£€•.,?!’(?!\w))**

<img width="1161" alt="Screenshot 2020-10-08 at 3 29 20 PM" src="https://user-images.githubusercontent.com/4289654/95444179-274e4380-097b-11eb-9a43-02ad98ecf12f.png">

**Comment by 2000calories** [comment]
try master branch
```
  easy_rich_text:
    git:
      url: https://github.com/2000calories/flutter_easy_rich_text.git
      ref: master
```

**Comment by nirajjoshi** [comment]
> try master branch and set `hasSpecialCharacters: true`
> 
> ```
> EasyRichText(
>   "Tap recognizer to print this sentence. ~|[]{}#%^*+=_\|<>\$£€•.,?!’",
>   patternList: [
>     EasyRichTextPattern(
>       targetString: '~|[]{}#%^*+=_|<>\$£€•.,?',
>       hasSpecialCharacters: true,
>       recognizer: TapGestureRecognizer()
>         ..onTap = () {
>           print("Tap recognizer to print this sentence.");
>         },
>       style: TextStyle(
>         decoration: TextDecoration.underline,
>       ),
>     ),
>   ],
> ),
> ```
> 
> ```
>   easy_rich_text:
>     git:
>       url: https://github.com/2000calories/flutter_easy_rich_text.git
>       ref: master
> ```

Thanks @2000calories . It worked.
Please update pub version with this fix at https://pub.dev/packages/easy_rich_text as well.

**Comment by 2000calories** [comment]
updated

**Comment by nirajjoshi** [comment]
> updated

Thanks.
