### ISSUE TITLE
无法匹配数字

### ISSUE THREAD

**Issue by Faith-zq** [2000calories/flutter_easy_rich_text#8]

**Comment by 2000calories** [comment]
![Screenshot_1604227041-1](https://user-images.githubusercontent.com/25191098/97800612-99136780-1c71-11eb-901f-c12af22ea582.png)
可以提供细节吗？我测试是可以的。
```
  EasyRichText("This is a test number 1", patternList: [
    EasyRichTextPattern(
      targetString: "1",
      style: TextStyle(color: Colors.blue),
    ),
  ]),
```

**Comment by CivelXu** [comment]
EasyRichText("1This is a test number 1", patternList: [
    EasyRichTextPattern(
      targetString: "1",
      style: TextStyle(color: Colors.blue),
    ),
  ]),

试一下

**Comment by 2000calories** [comment]
加上`matchWordBoundaries: false,`
默认是为英文设计的，会有word boundary，目标词是数字或字母但左右文本是中文的话，需要这样设置。
```
EasyRichText("哈哈60s未操作", patternList: [
  EasyRichTextPattern(
    targetString: "60",
    matchWordBoundaries: false,
    style: TextStyle(color: Colors.blue),
  ),
]),

```

**Comment by 2000calories** [comment]
Hi CivelXu, I will close this issue if you have no more feedback. You can re-open it anytime if you still have problem
