### ISSUE TITLE
Web: Safari compatibility

### ISSUE THREAD

**Issue by HBHXTRA** [2000calories/flutter_easy_rich_text#9]
When I run my code in safari it shows a grey or green canvas with nothing it.
Just a container grey or green.

**Comment by 2000calories** [comment]
Can you post your code?

**Comment by HBHXTRA** [comment]
Sure.

import 'package:easy_rich_text/easy_rich_text.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

class Logo extends StatelessWidget {
  final Color color;
  final bool large;
  const Logo({Key key, this.color, this.large}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Hero(
        tag: 'logo',
        child: Material(
          color: Colors.transparent,
          child: FittedBox(
            fit: BoxFit.scaleDown,
            child: EasyRichText(
              'T3 by TEST',
              defaultStyle: Get.textTheme.headline6
                  .copyWith(color: Get.theme.colorScheme.onSurface),
              patternList: [
                EasyRichTextPattern(
                  targetString: '3',
                  matchWordBoundaries: false,
                  style: TextStyle(color: Get.theme.colorScheme.primary),
                ),
                EasyRichTextPattern(
                  subScript: true,
                  targetString: 'by TEST',
                  style: TextStyle(color: Get.textTheme.caption.color),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

Even without Hero

**Comment by 2000calories** [comment]
Hi HBHXTRA, I did not figure it out. Have you tried the built-in `RichText` widget? Is it works?

**Comment by HBHXTRA** [comment]
No. I’ll give a try

**Comment by 2000calories** [comment]
Any update?

**Comment by HBHXTRA** [comment]
Works well with the OOB but with this plugin does not work on safari

**Comment by 2000calories** [comment]
Sorry no idea😂
